version: "3.8"
services:
  dvwa:
    image: vulnerables/web-dvwa
    ports:
      - "8081:80"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=dvwa
    restart: always

  juice-shop:
    image: bkimminich/juice-shop
    ports:
      - "3000:3000"
    restart: always

  bwapp:
    image: raesene/bwapp
    ports:
      - "8082:80"
    restart: always

  redis-vuln:
    image: redis:5.0.7
    command: redis-server --appendonly yes --protected-mode no
    ports:
      - "6379:6379"
    restart: always
